### ISSUE TITLE
Update documentation for get_prism_normals() to reflect new normal period

### ISSUE THREAD

**Issue by jessicaguo** [ropensci/prism#111]
Hi there! Had a quick question about `get_prism_normals()`  - the documentation states that it is currently computed using1981-2010, but the [linked page](https://prism.nacse.org/normals/) indicates 1991-2020. Which one is it, and if it has migrated to 1991-2020, how can I obtain the 1981-2010 normals?

**Comment by rabutler-usbr** [comment]
Ah, good catch @jessicaguo . They recently (sort of) rolled the 30-year period forward from 1981-2010 to 1991-2020, and I haven't updated the documentation since that roll forward. 

I think you could calculate the 1981-2010 average from the annual data using `get_prism_annual()`. I can't say I've done this, so might be good to compute the 1991-2020 average and compare to their normal period to verify the calculation is similar to theirs.
