### ISSUE TITLE
Download warning "error 1 in extracting from zip file"

### ISSUE THREAD

**Issue by LouiseJSlater** [ropensci/prism#45]
After running the line:
get_prism_monthlys(type="ppt", year = 1962:1962, month = 1:12, keepZip=F)

the data downloads, then self-deletes, with the warning:
"Error in process_zip(all_file, to_split) : Fix errors in process_zip
In addition: Warning message:
In unzip(outFile, exdir = strsplit(outFile, ".zip")[[1]]) :
  error 1 in extracting from zip file"

If I run the same line with the option "keepZip=T", the data downloads (without deleting), with the warning:
"Error in process_zip(all_file, to_split) : Fix errors in process_zip"

**Comment by kendonB** [comment]
The package doesn't yet support downloads of monthly data before 1981. This is in the pipeline though.

**Comment by LouiseJSlater** [comment]
Ah that makes sense then. Thanks so much for answering and apologies for flagging it up as an error!

**Comment by kendonB** [comment]
Hi Louise, flagging errors is totally the right thing to do on Github. My personal opinion is that people should generally 1) google the error, 2) search the error in the github issues and then 3) if still necessary file an issue. I usually leave developers to close issues unless I realize the problem was 100% user error.

**Comment by LouiseJSlater** [comment]
thanks Kendon :)

**Comment by emhart** [comment]
@LouiseJSlater This was working at one point, I'm reworking the package a bit and hopefully will have a fix for this soon.

**Comment by kendonB** [comment]
Fixed in ``83321a7``.
